# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 25) do

  create_table "_roles", :id => false, :force => true do |t|
    t.column "user_id", :integer, :default => 0, :null => false
    t.column "role_id", :integer, :default => 0, :null => false
  end

  create_table "advertisements", :force => true do |t|
    t.column "desc", :string, :default => "", :null => false
    t.column "priority", :integer
    t.column "placement", :string, :default => "", :null => false
    t.column "width", :string, :limit => 8, :default => "", :null => false
    t.column "height", :string, :limit => 8, :default => "", :null => false
    t.column "codeblock", :text, :default => "", :null => false
    t.column "enabled", :integer, :default => 0
    t.column "start_at", :datetime
    t.column "expire_at", :datetime
  end

  create_table "categories", :force => true do |t|
    t.column "category_name", :string, :default => "", :null => false
  end

  create_table "comments", :force => true do |t|
    t.column "submission_id", :integer
    t.column "root_id", :integer
    t.column "parent_id", :integer
    t.column "depth", :integer
    t.column "lft", :integer
    t.column "rgt", :integer
    t.column "updated_at", :datetime
    t.column "created_at", :datetime
    t.column "user_name", :string, :limit => 80, :default => "", :null => false
    t.column "user_id", :integer
    t.column "subject", :string, :default => "", :null => false
    t.column "body", :text, :default => "", :null => false
  end

  add_index "comments", ["submission_id"], :name => "submission_id_idx"

  create_table "friends", :force => true do |t|
    t.column "user_id", :integer
    t.column "profile_id", :integer
  end

  add_index "friends", ["user_id"], :name => "user_id_idx"
  add_index "friends", ["profile_id"], :name => "profile_id_idx"

  create_table "permissions", :force => true do |t|
    t.column "controller", :string, :default => "", :null => false
    t.column "action", :string, :default => "", :null => false
    t.column "description", :string
  end

  create_table "permissions_roles", :id => false, :force => true do |t|
    t.column "permission_id", :integer, :default => 0, :null => false
    t.column "role_id", :integer, :default => 0, :null => false
  end

  add_index "permissions_roles", ["permission_id"], :name => "permission_id_idx"
  add_index "permissions_roles", ["role_id"], :name => "role_id_idx"

  create_table "profile_flops", :force => true do |t|
    t.column "user_id", :integer
    t.column "profile_id", :integer
    t.column "created_at", :datetime
  end

  add_index "profile_flops", ["user_id"], :name => "user_id_idx"
  add_index "profile_flops", ["profile_id"], :name => "profile_id_idx"

  create_table "profile_pops", :force => true do |t|
    t.column "user_id", :integer
    t.column "profile_id", :integer
    t.column "created_at", :datetime
  end

  add_index "profile_pops", ["user_id"], :name => "user_id_idx"
  add_index "profile_pops", ["profile_id"], :name => "profile_id_idx"

  create_table "profiles", :force => true do |t|
    t.column "user_id", :integer
    t.column "image_url", :string, :default => ""
    t.column "description", :text, :default => "", :null => false
    t.column "dateofbirth", :datetime
    t.column "location", :string, :limit => 128, :default => ""
    t.column "country", :string, :limit => 128, :default => ""
    t.column "vote_total", :integer, :default => 0
    t.column "allow_email", :integer, :limit => 4, :default => 0
  end

  add_index "profiles", ["user_id"], :name => "user_id_idx"
  add_index "profiles", ["vote_total"], :name => "vote_total_idx"

  create_table "roles", :force => true do |t|
    t.column "name", :string, :default => "", :null => false
    t.column "description", :string
    t.column "omnipotent", :boolean, :default => false, :null => false
    t.column "system_role", :boolean, :default => false, :null => false
  end

  create_table "search_terms", :force => true do |t|
    t.column "term", :string
  end

  create_table "search_terms_submissions", :force => true do |t|
    t.column "search_term_id", :integer
    t.column "submission_id", :integer
  end

  add_index "search_terms_submissions", ["search_term_id"], :name => "search_term_id_idx"
  add_index "search_terms_submissions", ["submission_id"], :name => "submission_id_idx"

  create_table "search_terms_users", :force => true do |t|
    t.column "search_term_id", :integer
    t.column "user_id", :integer
  end

  add_index "search_terms_users", ["search_term_id"], :name => "search_term_id_idx"
  add_index "search_terms_users", ["user_id"], :name => "user_id_idx"

  create_table "sessions", :force => true do |t|
    t.column "session_id", :string
    t.column "data", :text
    t.column "updated_at", :datetime
    t.column "created_at", :datetime
  end

  add_index "sessions", ["session_id"], :name => "sessions_sessid_index"

  create_table "sub_blips", :force => true do |t|
    t.column "user_id", :integer
    t.column "submission_id", :integer
    t.column "created_at", :datetime
    t.column "bliptype", :integer
  end

  add_index "sub_blips", ["user_id"], :name => "user_id_idx"
  add_index "sub_blips", ["submission_id"], :name => "submission_id_idx"

  create_table "sub_flops", :force => true do |t|
    t.column "user_id", :integer
    t.column "submission_id", :integer
    t.column "created_at", :datetime
  end

  add_index "sub_flops", ["user_id"], :name => "user_id_idx"
  add_index "sub_flops", ["submission_id"], :name => "submission_id_idx"

  create_table "sub_pops", :force => true do |t|
    t.column "user_id", :integer
    t.column "submission_id", :integer
    t.column "created_at", :datetime
  end

  add_index "sub_pops", ["user_id"], :name => "user_id_idx"
  add_index "sub_pops", ["submission_id"], :name => "submission_id_idx"

  create_table "submissions", :force => true do |t|
    t.column "url", :string, :default => "", :null => false
    t.column "magnet_url", :string, :default => "", :null => false
    t.column "rss_url", :string, :default => "", :null => false
    t.column "torrent_url", :string, :default => "", :null => false
    t.column "user_id", :integer
    t.column "title", :string, :default => "", :null => false
    t.column "description", :text, :default => "", :null => false
    t.column "category", :string, :limit => 30, :default => "0", :null => false
    t.column "image_url", :string, :default => ""
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
    t.column "pfc", :integer, :limit => 4
    t.column "status", :integer, :limit => 40
    t.column "deleted", :datetime
    t.column "vote_total", :integer, :default => 0
    t.column "itunes_url", :string, :default => "", :null => false
  end

  add_index "submissions", ["user_id"], :name => "user_id_idx"
  add_index "submissions", ["vote_total"], :name => "vote_total_idx"
  add_index "submissions", ["category"], :name => "category_idx"

  create_table "taggings", :force => true do |t|
    t.column "tag_id", :integer
    t.column "taggable_id", :integer
    t.column "taggable_type", :string
  end

  add_index "taggings", ["tag_id"], :name => "tag_id_idx"
  add_index "taggings", ["taggable_id"], :name => "taggable_id_idx"
  add_index "taggings", ["taggable_type"], :name => "taggable_type_idx"

  create_table "tags", :force => true do |t|
    t.column "name", :string
  end

  create_table "urlnames", :force => true do |t|
    t.column "nameable_type", :string
    t.column "nameable_id", :integer
    t.column "name", :string
  end

  add_index "urlnames", ["nameable_id"], :name => "nameable_id_idx"
  add_index "urlnames", ["nameable_type"], :name => "nameable_type_idx"

  create_table "users", :force => true do |t|
    t.column "login", :string, :limit => 80, :default => "", :null => false
    t.column "salted_password", :string, :limit => 40, :default => "", :null => false
    t.column "email", :string, :limit => 60, :default => "", :null => false
    t.column "firstname", :string, :limit => 40
    t.column "lastname", :string, :limit => 40
    t.column "salt", :string, :limit => 40, :default => "", :null => false
    t.column "verified", :integer, :default => 0
    t.column "role", :string, :limit => 40
    t.column "security_token", :string, :limit => 40
    t.column "token_expiry", :datetime
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
    t.column "logged_in_at", :datetime
    t.column "deleted", :integer, :default => 0
    t.column "delete_after", :datetime
    t.column "registered_from_ip", :string, :default => "", :null => false
    t.column "remember_token", :string
    t.column "remember_token_expires", :datetime
  end

end
